export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const SEARCH_MOVIE_LOADING = "SEARCH_MOVIE_LOADING";
export const MOVIE_LOADING = "MOVIE_LOADING";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
